version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: eduplatform_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: eduplatform_user
      POSTGRES_PASSWORD: eduplatform_pass
      POSTGRES_DB: eduplatform_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    name: eduplatform_postgres_data